import {
  DEFAULT_CONTENT_COMMANDS_CONFIG,
  DEFAULT_FORMAT_COMMANDS_CONFIG,
  DEFAULT_EXPORT_COMMANDS_CONFIG,
} from './commands';

export const DEFAULT_EDITOR_OPERATORS = {
  ...DEFAULT_CONTENT_COMMANDS_CONFIG,
  ...DEFAULT_FORMAT_COMMANDS_CONFIG,
  ...DEFAULT_EXPORT_COMMANDS_CONFIG,
};

// 这些常量已经移动到 editor.ts 中，这里保留是为了向后兼容
export {
  DEFAULT_EDITOR_ID,
  DEFAULT_EDITOR_CONTENT,
  DEFAULT_MAX_HISTORY_SIZE,
  DEFAULT_AUTO_SAVE_INTERVAL,
} from './editor';
